## Header ----
## Pipeline to extract vegetation indices from orthomosaics and
## Shape file clips
## Author: Simon Treier adapted by Nicolas Vuille-dit-Bille
## Starting date: 16. August 2018
## Last modification: 10.01.2024

# To execute these R-script, a specific folder structure has to be met. In the working directory,
# three folders have to be created, named exactly as follows (mind capital and lower case letters).
# .	Ortho
# .	CompleteBlockSHP
# .	ClippingSHP
# "Ortho" contains all Orthofiles that are to be examined. The orthofile names must be as follows:
# Country.ZIP.Plot.YearMonthDay.FlightHight.Further-Info(Such as Data shown).tif
#
# Examples:
# CH.1260.P051.20190926.30m.RGB.tif
# CH.1260.P051.20190926.30m.RGN.tif
# CH.1260.P051.20190926.30m.DEM.tif
#
# The date of recording must be in a 8 digit format as follows: YYYYMMDD. The .tif name mustn't contain any
# other sequence of eight digits.
# "CompleteBlockSHP" must contain one shape file of an area that covers all plots which are to be examined
# in the subsequent data-extraction process (i.e. the total of the experimental units), but it should not be
# much bigger. This will allow the algorithm to be more efficient, as this reduces the amount of RAM needed.
# This file will also contain the accompanying files that come with the shape file (they are automatically
# generated by Qgis and have the same name but a different ending than the shape file).
# Finally, the folder "ClippingSHP" contains all the shapefiles and accompanying files of the ROI's, i.e. all the
# experimental units.

## Color space definition ----
## Enter color space (RGB or RGB)
install.packages("stringr")
install.packages("data.table")
install.packages("dplyr")
install.packages("sf")


ColorSpace <- "DUO"

## Packages ----
library(raster)
library(stringr)
library(data.table)
library(dplyr)
library(sf)

#install.packages('data.table')
#install.packages('sf')
## Set WD ----
mainDir <- "O:/Data-Work/22_Plant_Production-CH/224_Digitalisation/Experiments/2023/LP01/Data/Drone/CH/Process"  # Define working Directory
setwd(mainDir) # Set working Directory

## Load orthofile names ----
Orthofiles <- list.files(path="Ortho",pattern="*.tif", full.names=TRUE, recursive=FALSE)
Orthofiles 
Orthofilenames <- gsub("Ortho/","",Orthofiles)
Orthofilenames
## Extract Information from Orthofilename ----
Imageinform <- as.data.table(Orthofilenames);
Imageinform 

Imageinform[, c("Country","ZIP","Plot","Dates","FlightHight","Datatype","Fileformat") := do.call(Map, c(f = c, strsplit(Orthofilenames,'[.]',fixed = FALSE))) ]
Imageinform 

DateHight <- paste0(Imageinform$Dates, ".", Imageinform$FlightHight);DateHight
## OGR stands for :OpenGIS Simple Features Reference Implementation
## https://de.wikipedia.org/wiki/Geospatial_Data_Abstraction_Library
## Check and create data structure ----
for(j in 1:length(Orthofiles)){ # Check if date-folder exists, if not, create one
  # Check if date-folder exists
  if (file.exists(DateHight[j])){
  } else {
    dir.create(file.path(mainDir, DateHight[j]))
  }
  
  FolderPath <- (paste0(DateHight[j],"/",ColorSpace)) # Create colorspace path
  if (file.exists(FolderPath)){ # Check if color space folder exists
  } else {
    dir.create(file.path(mainDir, FolderPath))
  }
  
  ## Load orthomosaic and crop to size of interest ----
  intif_Raw <- stack(Orthofiles[j]) # Load orthomosaic
  
  #### Automatic segmentation ###
  
  # N<-intif_Raw[[10]]
  # Re<-intif_Raw[[9]]
  # R<-intif_Raw[[6]]
  # G<-intif_Raw[[4]]
  # B<-intif_Raw[[2]]
  # RGB<-stack(c(B,G,R,Re,N))
  # intif_Raw2<- fieldMask(mosaic =RGB, Red = 3, Green = 2, Blue = 1, RedEdge=4, NIR=5, index = "BGI",cropValue=0.45, cropAbove = T)
  # EX.HYP.S<-fieldMask(Orthofiles[j],mask = intif_Raw2$mask, plot = F)
  intif <- intif_Raw
  
  MainPlot <- list.files(path="CompleteBlockSHP",pattern="*.shp", full.names=TRUE, recursive=FALSE) # Load contours of the experimental plot of interest (subset of orthomosaic that covers the area of all subplot of the experiment of interest)
  crop_extent <- st_read(MainPlot) # Load file
  # intif_crop <- crop(intif, crop_extent) # Crop the orthomosaic with the contours of the experiment
  NtrialCropped <- crop(intif, crop_extent) # Crop the orthomosaic with the contours of the experiment
  rm(intif) # Remove the large orthomosaic and just keep the area of the experiment (that contains all the subplots of interest)
  Folderfiles <- list.files(path="ClippingSHP",pattern="*.shp", full.names=TRUE, recursive=FALSE)# Create a list of all subplots in the folder "Clipping SHP"
  ## Define Output Structure ----
  ## Create a table where values can be written in with the lenth of the number of .shp files in folders
  Stat_data <- NULL
  names <- c("Index","ID","Name","Mean","sd") # Create names of the head of the rows of the datatable
  QuantilesDecimDigits <- seq(0.1,0.6,0.1) # Create quantiles for a certain range 1
  QuantilesCentiDigits1 <- seq(0.64,0.8,0.04) # Create quantiles for a certain range 2
  QuantilesCentiDigits2 <- seq(0.82,0.98,0.02) # Create quantiles for a certain range 3
  Quantiles <- c(QuantilesDecimDigits,QuantilesCentiDigits1,QuantilesCentiDigits2) # Create vector with all quantiles of interest
  Quantilenames <- paste0("Q",Quantiles) # Add Q to quantiles
  Tablenames <- c(names, Quantilenames,"Date.and.Flight.Hight","Orthofile") # Add names, quantilenames and introduce a DateFlightHight ID and a separate orthofilename
  
  Stat_data <- data.frame(matrix(NA, nrow = length(Folderfiles), ncol = length(Tablenames))) # Create a table where values can be written in with the length of the number of .shp files in folders and a number of colomns corresponding to the entries per index per plot
  names(Stat_data) <- Tablenames # Add the names to the Stat_Data table
  
  # In the following:
  # StatNewRow: A line that includes the values of one index of one plot
  # Stat_data_Line: Building up to a file that includes the values of all indices of one plot
  # Stat_data: All values of one date.hight (all indices of all plots)
  # CompleteData:  All values of all dates (all indices of all plots of all dates)
  
  ## Extract data from each subplot from each orthomosaic ----
  for(i in 1:length(Folderfiles)){ # Loop for all subplots in the orthomosaic
    plot_extent <- st_read(Folderfiles[i]) # Set extend of subplot i
    intif_plot <- crop(NtrialCropped, plot_extent) # Crop subplot from allready cropped orthomosaic
    plot<-mask(intif_plot, plot_extent, overwrite=TRUE) # Mask cropped subplot
    outfile <- gsub("ClippingSHP/","",Folderfiles[i]) # Create the name that can be used for identifying outputs
    outpath <- paste(FolderPath,"/",outfile, sep="") # Path in case that visual index results or histograms are to be exported

########## MXBLUE BANDS #####################################

    #Multispectral indices
    B_MCARI705_MTVI2_Arg <- (((plot[[7]]-plot[[5]])-0.2*(plot[[7]]-plot[[3]]))*(plot[[7]]/plot[[5]]))/ (1.5*(2.5*(plot[[10]]-plot[[5]])-1.3*(plot[[10]]-plot[[3]]))/((2*plot[[10]]+1)^2-(6*plot[[10]]-5*plot[[5]]^0.5))^0.5) #Ratio of Modified chlorophyll absorption in reflectance index with Rede705 with MTVI2_Arg // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.// (Basso et al. 2016)
    B_MCARI740_MTVI2_Arg <- (((plot[[9]]-plot[[5]])-0.2*(plot[[9]]-plot[[3]]))*(plot[[9]]/plot[[5]]))/ (1.5*(2.5*(plot[[10]]-plot[[5]])-1.3*(plot[[10]]-plot[[3]]))/((2*plot[[10]]+1)^2-(6*plot[[10]]-5*plot[[5]]^0.5))^0.5)#Ratio of Modified chlorophyll absorption in reflectance index with Rede740 with MTVI2_Arg // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.// (Basso et al. 2016)
    
    
    B_MCARI705_MTVI <- (((plot[[7]]-plot[[5]])-0.2*(plot[[7]]-plot[[3]]))*(plot[[7]]/plot[[5]]))/(1.2*(1.2 * (plot[[10]] - plot[[3]])-2.5*(plot[[5]]-plot[[3]]))) # Ratio of Modified chlorophyll absorption in reflectance index with Rede705 with MTVI // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.// (Basso et al. 2016)
    B_MCARI740_MTVI <- (((plot[[9]]-plot[[5]])-0.2*(plot[[9]]-plot[[3]]))*(plot[[9]]/plot[[5]]))/(1.2*(1.2 * (plot[[10]] - plot[[3]])-2.5*(plot[[5]]-plot[[3]]))) # Ratio of Modified chlorophyll absorption in reflectance index with Rede740 with MTVI // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.//(Basso et al. 2016)
    
    
    B_MCARI705_OSAVI_B<- (((plot[[7]]-plot[[5]])-0.2*(plot[[7]]-plot[[5]]))*(plot[[7]]/plot[[5]]))/ ((1 + 0.16)*(plot[[10]] - plot[[5]])/(plot[[10]] + plot[[5]] + 0.16)) # Ratio of Modified chlorophyll absorption in reflectance index with Rede705 with OSAVI_B // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.//(Basso et al. 2016)
    B_MCARI740_OSAVI_B<- (((plot[[9]]-plot[[5]])-0.2*(plot[[9]]-plot[[5]]))*(plot[[9]]/plot[[5]]))/ ((1 + 0.16)*(plot[[10]] - plot[[5]])/(plot[[10]] + plot[[5]] + 0.16)) # Ratio of Modified chlorophyll absorption in reflectance index with Rede740 with OSAVI_B // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.//(Basso et al. 2016)
    
    
    B_TCARI705_OSAVI_B <- (3*((plot[[7]]-plot[[5]])-0.2*(plot[[7]]-plot[[3]])*(plot[[7]]/plot[[5]])))/((1 + 0.16)*(plot[[10]] - plot[[5]])/(plot[[10]] + plot[[5]] + 0.16)) # Ratio of TCARI with Re705 with OSAVI // Nitrogen// (Basso et al. 2016)
    B_TCARI740_OSAVI_B <- (3*((plot[[9]]-plot[[5]])-0.2*(plot[[9]]-plot[[3]])*(plot[[9]]/plot[[5]])))/((1 + 0.16)*(plot[[10]] - plot[[5]])/(plot[[10]] + plot[[5]] + 0.16)) # Ratio of TCARI with Re740 with OSAVI // Nitrogen// (Basso et al. 2016)
    
    B_NDRE705_NDVI <- ((plot[[10]]-plot[[7]])/(plot[[10]]+plot[[7]]))/((plot[[10]]-plot[[5]])/(plot[[10]]+plot[[5]])) # Ratio of Normalize difference red-edge index with NDVI (Chlorophll; Gitelson and Merzlyak 1994)//  (Basso et al. 2016)
    B_NDRE740_NDVI <- ((plot[[10]]-plot[[9]])/(plot[[10]]+plot[[9]]))/((plot[[10]]-plot[[5]])/(plot[[10]]+plot[[5]])) # Ratio of Normalize difference red-edge index with NDVI (Chlorophll; Gitelson and Merzlyak 1994) //  (Basso et al. 2016)
    
    
    B_NDVI_Re_705_NDVI <- ((plot[[7]]-plot[[5]])/(plot[[7]]+plot[[5]]))/((plot[[10]]-plot[[5]])/(plot[[10]]+plot[[5]])) # Ratio of Normalized difference vegetation index with rededge705 instaed of NIR with NDVI # NDRE1 according to Basso (Basso et al. 2016)
    B_NDVI_Re_740_NDVI <- ((plot[[9]])-(plot[[5]])/(plot[[9]]+plot[[5]]))/((plot[[10]]-plot[[5]])/(plot[[10]]+plot[[5]])) # Ratio of Normalized difference vegetation index with rededge740 instead of NIR with NDVI # NDRE1 according to Basso (Basso et al. 2016)
    
    B_TCARI705 <- 3*((plot[[7]]-plot[[5]])-0.2*(plot[[7]]-plot[[3]])*(plot[[7]]/plot[[5]])) # TCARI with Re705 // Nitrogen// (Basso et al. 2016)
    B_TCARI740 <- 3*((plot[[9]]-plot[[5]])-0.2*(plot[[9]]-plot[[3]])*(plot[[9]]/plot[[5]])) # TCARI with Re740 // Nitrogen// (Basso et al. 2016)
    
    B_CARI705 <- (plot[[7]] - plot[[5]]) - 0.2 * (plot[[7]] - plot[[3]]) # CARI with Re705 // Nitrogen// (Basso et al. 2016)
    B_CARI740 <- (plot[[9]] - plot[[5]]) - 0.2 * (plot[[9]] - plot[[3]]) # CARI with Re740 // Nitrogen// (Basso et al. 2016)
    
    B_MTCI705 <- (plot[[10]] - plot[[7]])/(plot[[7]] - plot[[5]]) # MTCI with Re705// Nitrogen //(Basso et al. 2016)
    B_MTCI740 <- (plot[[10]] - plot[[9]])/(plot[[9]] - plot[[5]]) # MTCI with Re740 // NItrogen // (Basso et al. 2016)
    
    B_SR <- plot[[10]]/plot[[5]] # simple ratio index // Easy to understand and is effective over a wide range of conditions //Can saturate in dense vegetation when LAI becomes very high.//  (Birth, G., and G. McVey. "Measuring the Color of Growing Turf with a Reflectance Spectrophotometer." Agronomy Journal 60 (1968): 640-643.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html # Also called RVI //Ratio vegetation index // Biomass, water content,nitrogen // Pearson and Miller (1972)//https://raw.githubusercontent.com/filipematias23/images/master/readme/F6ind3.jpeg 
    B_CRE705 <- plot[[10]]/plot[[7]] - 1 #  CRE with Re705// Nitrogen // (Basso et al. 2016)
    B_CRE740 <- plot[[10]]/plot[[9]] - 1 #  CRE with Re740 // Nitrogen //  (Basso et al. 2016)
    
    B_NDVI <- (plot[[10]]-plot[[5]])/(plot[[10]]+plot[[5]]) # Normalized difference vegetation index // measure of healthy, green vegetation // saturate in dense vegetation conditions when LAI becomes high.// Rouse, J., R. Haas, J. Schell, and D. Deering. Monitoring Vegetation Systems in the Great Plains with ERTS. Third ERTS Symposium, NASA (1973): 309-317. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    B_NDVI_Re_705 <- (plot[[7]]-plot[[5]])/(plot[[7]]+plot[[5]]) # Normalized difference vegetation index with rededge705 instaed of NIR # NDRE1 according to Basso (Basso et al. 2016)
    B_NDVI_Re_740 <- (plot[[9]])-(plot[[5]])/(plot[[9]]+plot[[5]]) # Normalized difference vegetation index with rededge740 instead of NIR # NDRE1 according to Basso (Basso et al. 2016)
    
    B_SAVI <- (1.5*(plot[[10]]-plot[[5]]))/(plot[[10]]+plot[[5]]+0.5) # Soil adjusted vegetation index // Best used in areas with relatively sparse vegetation where soil is visible through the canopy // similar to NDVI, but it suppresses the effects of soil pixels// Huete, A. "A Soil-Adjusted Vegetation Index (SAVI)." Remote Sensing of Environment 25 (1988): 295-309.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    B_MSAVI2 <-(2*plot[[10]]+1-sqrt((2*plot[[10]]+1)^2-8*(plot[[10]]-plot[[5]])))/2 # Modified soil adjusted vegetation index 2//  Reduces soil noise and increases the dynamic range of the vegetation signal //  Qi, J., A. Chehbouni, A. Huete, Y. Kerr, and S. Sorooshian. "A Modified Soil Adjusted Vegetation Index." Remote Sensing of Environment 48 (1994): 119-126. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    B_OSAVI <- (plot[[10]]-plot[[5]])/(plot[[10]]+plot[[5]]+0.16) # Optimized soil adjusted vegetation index // This index is best used in areas with relatively sparse vegetation where soil is visible through the canopy // Rondeaux, G., M. Steven, and F. Baret. "Optimization of Soil-Adjusted Vegetation Indices." Remote Sensing of Environment 55 (1996): 95-107. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    B_OSAVI_B <- (1 + 0.16)*(plot[[10]] - plot[[5]])/(plot[[10]] + plot[[5]] + 0.16) # Optimized soil adjusted vegetation index based on Basso publication // (Basso et al. 2016)
    
    B_EVI <- 2.5*(plot[[10]]-plot[[5]])/(plot[[10]]+6*plot[[5]]-7.5*plot[[1]]+1) # Enhanced vegetation index //Improvement over NDVI by optimizing the vegetation signal in areas of high leaf area index (LAI)//Huete, A., et al. "Overview of the Radiometric and Biophysical Performance of the MODIS Vegetation Indices."Remote Sensing of Environment 83 (2002):195-213. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    B_TVI_R <- sqrt((plot[[10]]-plot[[5]])/(plot[[10]]+plot[[5]])+0.05) # Triangular vegetation index // can be utilized to follow grain crop development from seed bed preparation to harvest// Rouse Jr, J. W., Haas, R. H., Deering, D. W., Schell, J. A., & Harlan, J. C. (1974). Monitoring the vernal advancement and retrogradation (green wave effect) of natural vegetation (No. E75-10354).
    
    # N content in canopy indices
    B_MTVI <- 1.2*(1.2 * (plot[[10]] - plot[[3]])-2.5*(plot[[5]]-plot[[3]]))# Nitrogen // (Basso et al. 2016)
    B_MTVI2_Arg <- 1.5*(2.5*(plot[[10]]-plot[[5]])-1.3*(plot[[10]]-plot[[3]]))/((2*plot[[10]]+1)^2-(6*plot[[10]]-5*plot[[5]]^0.5))^0.5 # modified triangular vegetation index 2 // Canopy N content prediction //  Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.
    B_MTVI2_Hab <- (1.5*(1.2*(plot[[10]]-plot[[3]])-2.5*(plot[[5]]-plot[[3]])))/(sqrt((2*plot[[10]]+1)^2-(6*plot[[10]]-5*sqrt(plot[[5]]))-0.5)) # (Haboudane et al., 2004.) (Bagheri et al. 2013)(Basso et al. 2016)
    B_MCARI_Arg705 <- ((plot[[7]]-plot[[5]])-0.2*(plot[[7]]-plot[[3]]))*(plot[[7]]/plot[[5]]) # Modified chlorophyll absorption in reflectance index with Rede705 // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.
    B_MCARI_Arg740 <- ((plot[[9]]-plot[[5]])-0.2*(plot[[9]]-plot[[3]]))*(plot[[9]]/plot[[5]]) # Modified chlorophyll absorption in reflectance index with Rede740 // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.
    B_MCARI2_Hab <- (1.5*(2.5*(plot[[10]]-plot[[5]])-1.3*(plot[[10]]-plot[[3]])))/(sqrt((2*plot[[10]]+1)^2-(6*plot[[10]]-5*sqrt(plot[[5]]))-0.5)) # Modified Chlorophyll Absorption Ratio Index Improved // similar to MCARI but is considered a better predictor of green leaf area index (LAI). It incorporates a soil adjustment factor while preserving sensitivity to LAI and resistance to chlorophyll influence.// Haboudane, D., et al. "Hyperspectral Vegetation Indices and Novel Algorithms for Predicting Green LAI of Crop Canopies: Modeling and Validation in the Context of Precision Agriculture." Remote Sensing of Environment 90 (2004): 337-352. // https://www.l3harrisgeospatial.com/docs/narrowbandgreenness.html 
    
    # Chlorophyll index
    
    B_CVI <- (plot[[10]]*plot[[5]])/(plot[[3]]^2) # Chlorophyll vegetation index // Vincini, M., Frazzi, E. R. M. E. S., & D'Alessio, P. A. O. L. O. (2008). A broad-band leaf chlorophyll vegetation index at the canopy scale. Precision Agriculture, 9(5), 303-319. // https://raw.githubusercontent.com/filipematias23/images/master/readme/F6ind3.jpeg
    B_CVI_B <- (plot[[10]]/plot[[3]]) * (plot[[5]]/plot[[3]]) # Chlorophyll vegetation index //(Basso et al. 2016)
    B_gNDVI <- (plot[[10]]-plot[[3]])/(plot[[10]]+plot[[3]]) # Green normalized difference vegetation index // similar to NDVI except that it measures the green spectrum from 540 to 570 nm instead of the red spectrum. This index is more sensitive to chlorophyll concentration than NDVI //Gitelson, A., and M. Merzlyak. "Remote Sensing of Chlorophyll Concentration in Higher Plant Leaves." Advances in Space Research 22 (1998): 689-692.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green
    B_GCI <- (plot[[10]]/plot[[3]])-1 # Green Chlorophyll Index // This index is used to estimate leaf chlorophyll content across a wide range of plant species. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green // Gitelson, A., Y. Gritz, and M. Merzlyak. "Relationships Between Leaf Chlorophyll Content and Spectral Reflectance and Algorithms for Non-Destructive Chlorophyll Assessment in Higher Plant Leaves." Journal of Plant Physiology 160 (2003): 271-282.
    # and Cholorophyll index-green (chlorophyll;Gitelson et al. 2003)
    
    #RGB indices
    
    B_GLI_Har <- ((plot[[3]]-plot[[5]])+(plot[[3]]-plot[[1]]))/((2*plot[[3]])+plot[[5]]+plot[[1]]) # Green Leaf Index // This index was originally designed for use with a digital RGB camera to measure wheat cover, where the red, green, and blue digital numbers (DNs) range from 0 to 255 // Louhaichi, M., M. Borman, and D. Johnson. "Spatially Located Platform and Aerial Photography for Documentation of Grazing Impacts on Wheat." Geocarto International 16, No. 1 (2001): 65-70. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green
    B_NGRDI <- (plot[[3]]-plot[[5]])/(plot[[3]]+plot[[5]]) # Normalized green red difference index // Chlorophyll, biomass and water content prediction // Tucker, C. J. (1979). Red and photographic infrared linear combinations for monitoring vegetation. Remote sensing of Environment, 8(2), 127-150.// https://raw.githubusercontent.com/filipematias23/images/master/readme/F6ind3.jpeg
    B_VARI <- (plot[[3]]-plot[[5]])/(plot[[3]]+plot[[5]]-plot[[1]]) # Visible atmospherically resistant index // This index is based on the ARVI and is used to estimate the fraction of vegetation in a scene with low sensitivity to atmospheric effects.// Gitelson, A., et al. "Vegetation and Soil Lines in Visible Spectral Space: A Concept and Technique for Remote Estimation of Vegetation Fraction. International Journal of Remote Sensing 23 (2002): 2537???2562.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green
    
    B_TGI <- plot[[3]]-0.39*plot[[5]]-0.61*plot[[1]] # Triangular greenness index surrogate, following https://agribotix.com/blog/2017/04/30/comparing-rgb-based-vegetation-indices-with-ndvi-for-agricultural-drone-imagery// From Simon Treier
    B_TGI_Har <- ((650-444)*(plot[[5]]-plot[[3]])-(650-531)*(plot[[5]]-plot[[1]]))/2 # Triangular Greenness Index // The TGI is highly correlated with leaf chlorophyll content.// Hunt, E., C. Daughtry, J. Eitel, and D. Long. "Remote Sensing Leaf Chlorophyll Content Using a Visible Band Index." Agronomy Journal 103, No. 4 (2011): 1090-1099.//https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Visible
    
    B_MNVI <- 2*(plot[[3]])-2*(plot[[1]])-2.4*(plot[[5]]) # // difference between the excess green (EGVI = 2G-R-B) and excess red (ERVI = 1.4R-B) // plant density prediction // Jin, X., Liu, S., Baret, F., Hemerl?, M., & Comar, A. (2017). Estimates of plant density of wheat crops at emergence from very low altitude UAV imagery. Remote Sensing of Environment, 198, 105-114.
    
    #Other multispectral indices
    
    B_DVI <- plot[[10]]-plot[[5]] # Difference Vegetation Index // distinguishes between soil and vegetation, but it does not account for the difference between reflectance and radiance caused by atmospheric effects or shadows.// Tucker, C. "Red and Photographic Infrared Linear Combinations for Monitoring Vegetation. Remote Sensing of Environment 8 (1979): 127-150. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Differen
    B_GEMI <- ((2*(plot[[10]]^2-plot[[5]]^2)+1.5*plot[[10]]+0.5*plot[[5]])/(plot[[10]]+plot[[5]]+0.5))*(1-0.25*((2*(plot[[10]]^2-plot[[5]]^2)+1.5*plot[[10]]+0.5*plot[[5]])/(plot[[10]]+plot[[5]]+0.5)))-(plot[[5]]-0.125)/(1-plot[[5]]) # Global Environmental Monitoring Index // It is similar to NDVI but is less sensitive to atmospheric effects // It is affected by bare soil; therefore, it is not recommended for use in areas of sparse or moderately dense vegetation. // Pinty, B., and M. Verstraete. GEMI: a Non-Linear Index to Monitor Global Vegetation From Satellites. Vegetation 101 (1992): 15-20. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Global
    B_GARI <- (plot[[10]]-(plot[[3]]-1.7*(plot[[1]]-plot[[5]])))/(plot[[10]]+(plot[[3]]-1.7*(plot[[5]]-plot[[1]]))) # Green Atmospherically Resistant Index // more sensitive to a wide range of chlorophyll concentrations and less sensitive to atmospheric effects than NDVI. // Gitelson, A., Y. Kaufman, and M. Merzylak. "Use of a Green Channel in Remote Sensing of Global Vegetation from EOS-MODIS." Remote Sensing of Environment 58 (1996): 289-298. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green2
    B_GDVI <- plot[[10]]-plot[[3]] # Green Difference Vegetation Index // was originally designed with color-infrared photography to predict nitrogren requirements for corn.// Sripada, R., et al. "Determining In-Season Nitrogen Requirements for Corn Using Aerial Color-Infrared Photography." Ph.D. dissertation, North Carolina State University, 2005. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green2
    B_GOSAVI <- (plot[[10]]-plot[[3]])/(plot[[10]]+plot[[3]]+0.16) # Green Optimized Soil Adjusted Vegetation Index // designed with color-infrared photography to predict nitrogren requirements for corn. It is similar to OSAVI, but it substitutes the green band for red.//Sripada, R., et al. "Determining In-Season Nitrogen Requirements for Corn Using Aerial Color-Infrared Photography." Ph.D. dissertation, North Carolina State University, 2005.//https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green9 
    B_GRVI <- plot[[10]]/plot[[3]] # Green Ratio Vegetation Index //  sensitive to photosynthetic rates in forest canopies, as green and red reflectances are strongly influenced by changes in leaf pigments. // Sripada, R., et al. "Aerial Color Infrared Photography for Determining Early In-season Nitrogen Requirements in Corn." Agronomy Journal 98 (2006): 968-977.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green4
    B_GSAVI <- 1.5*(plot[[10]]-plot[[3]])/(plot[[10]]+plot[[3]]+0.5) # Green Soil Adjusted Vegetation Index // Originally designed with color-infrared photography to predict nitrogren requirements for corn. It is similar to SAVI, but it substitutes the green band for red.//Sripada, R., et al. "Determining In-Season Nitrogen Requirements for Corn Using Aerial Color-Infrared Photography." Ph.D. dissertation, North Carolina State University, 2005.//https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green8
    B_IPVI <- plot[[10]]/(plot[[10]]+plot[[5]]) # Infrared Percentage Vegetation Index//functionally the same as NDVI, but it is computationally faster. Values range from 0 to 1. // Crippen, R. "Calculating the Vegetation Index Faster." Remote Sensing of Environment 34 (1990): 71-73. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green4
    B_LAI <- 3.618*(2.5*(plot[[10]]-plot[[5]])/(plot[[10]]+6*plot[[5]]-7.5*plot[[1]]+1))-0.118 # Leaf Area Index // used to estimate foliage cover and to forecast crop growth and yield.// Boegh, E., H. Soegaard, N. Broge, C. Hasager, N. Jensen, K. Schelde, and A. Thomsen. "Airborne Multi-spectral Data for Quantifying Leaf Area Index, Nitrogen Concentration and Photosynthetic Efficiency in Agriculture." Remote Sensing of Environment 81, no. 2-3 (2002): 179-193. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Leaf
    B_GVI <- (-0.2848*plot[[1]])+(-0.2435*plot[[3]])+(-0.5436*plot[[5]])+(0.7243*plot[[10]]) # Green Vegetation Index // This index minimizes the effects of background soil while emphasizing green vegetation // Kauth, R., and G. Thomas. "The Tasselled Cap-A Graphic Description of the Spectral-Temporal Development of Agricultural Crops as Seen By Landsat" In Proceedings of the LARS 1976 Symposium of Machine Processing of Remotely-Sensed Data, West Lafayette, IN: Purdue University, pp. 4B41-4B51. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green5
    B_MNLI <- ((plot[[10]]^2-plot[[5]])*(1+0.5))/(plot[[10]]^2+plot[[5]]+0.5) # Modified Non-Linear Index // enhancement to the Non-Linear Index (NLI) that incorporates the Soil Adjusted Vegetation Index (SAVI) to account for the soil background // Yang, Z., P. Willis, and R. Mueller. "Impact of Band-Ratio Enhanced AWIFS Image to Crop Classification Accuracy." Proceedings of the Pecora 17 Remote Sensing Symposium (2008), Denver, CO. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Modified2
    B_MSR <- ((plot[[10]]/plot[[5]])-1)/((sqrt(plot[[10]]/plot[[5]]))+1) # Modified Simple Ratio // improvement over RDVI by combining the Simple Ratio into the formula. The result is increased sensitivity to vegetation biophysical parameters // Chen, J. "Evaluation of Vegetation Indices and Modified Simple Ratio for Boreal Applications." Canadian Journal of Remote Sensing 22 (1996): 229-242. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Modified
    B_NLI <- (plot[[10]]^2-plot[[5]])/(plot[[10]]^2+plot[[5]]) # Non-Linear Index // relationship between many vegetation indices and surface biophysical parameters is non-linear. // Goel, N., and W. Qin. "Influences of Canopy Architecture on Relationships Between Various Vegetation Indices and LAI and Fpar: A Computer Simulation." Remote Sensing Reviews 10 (1994): 309-347. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Non-Line
    B_RDVI <- (plot[[10]]-plot[[5]])/sqrt(plot[[10]]+plot[[5]]) # Renormalized Difference Vegetation Index // This index uses the difference between near-infrared and red wavelengths, along with the NDVI, to highlight healthy vegetation. It is insensitive to the effects of soil and sun viewing geometry.// Roujean, J., and F. Breon. "Estimating PAR Absorbed by Vegetation from Bidirectional Reflectance Measurements." Remote Sensing of Environment 51 (1995): 375-384.//https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Renormal
    B_TDVI <- 1.5*((plot[[10]]-plot[[5]])/sqrt(plot[[10]]^2+plot[[5]]+0.5)) # Transformed Difference Vegetation Index // Useful for monitoring vegetation cover in urban environments. It does not saturate like NDVI and SAVI.// Bannari, A., H. Asalhi, and P. Teillet. "Transformed Difference Vegetation Index (TDVI) for Vegetation Cover Mapping" In Proceedings of the Geoscience and Remote Sensing Symposium, IGARSS '02, IEEE International, Volume 5 (2002). // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Transfor2
    B_WDRVI <- (0.2*plot[[10]]-plot[[5]])/(0.2*plot[[10]]+plot[[5]]) # Wide Dynamic Range Vegetation Index // similar to NDVI, but it uses a weighting coefficient (a) to reduce the disparity between the contributions of the near-infrared and red signals to the NDVI. The WDRVI is particularly effective in scenes that have moderate-to-high vegetation density when NDVI exceeds 0.6. // Gitelson, A. "Wide Dynamic Range Vegetation Index for Remote Quantification of Biophysical Characteristics of Vegetation." Journal of Plant Physiology 161, No. 2 (2004): 165-173.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Wide
    
    B_WVVI_705 <- (plot[[10]]-plot[[5]])/(plot[[7]]+plot[[5]]) # WorldView Improved Vegetative Index // This index uses WorldView-2 bands (here replaced by red-edge band705) to compute NDVI.// Wolf, A. Using WorldView 2 Vis-NIR MSI Imagery to Support Land Mapping and Feature Extraction Using Normalized Difference Index Ratios. Unpublished report, Longmont, CO: DigitalGlobe (2010).// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#WorldVie2
    B_WVVI_740 <- (plot[[10]]-plot[[5]])/(plot[[9]]+plot[[5]]) #  WorldView Improved Vegetative Index // This index uses WorldView-2 bands (here replaced by red-edge band740) to compute NDVI.// Wolf, A. Using WorldView 2 Vis-NIR MSI Imagery to Support Land Mapping and Feature Extraction Using Normalized Difference Index Ratios. Unpublished report, Longmont, CO: DigitalGlobe (2010).// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#WorldVie2 
    
    B_MSR_Re_705 <- ((plot[[10]])/(plot[[7]])-1)/(((plot[[10]])/(plot[[7]])+1)^0.5) # Modified Simple Ratio with Rededge705 // Improve LAI prediction; The reﬂectance in the red-edge spectral region is comparatively sensitive to chlorophyll content which is highly variable between different crops and different phenological states // https://www.researchgate.net/publication/323723081_Vegetation_Indices_Combining_the_Red_and_Red-Edge_Spectral_Information_for_Leaf_Area_Index_Retrieval
    B_MSR_Re_740 <- ((plot[[10]])/(plot[[9]])-1)/(((plot[[10]])/(plot[[9]])+1)^0.5) # Modified Simple Ratio with Rededge740 // Improve LAI prediction; The reﬂectance in the red-edge spectral region is comparatively sensitive to chlorophyll content which is highly variable between different crops and different phenological states // https://www.researchgate.net/publication/323723081_Vegetation_Indices_Combining_the_Red_and_Red-Edge_Spectral_Information_for_Leaf_Area_Index_Retrieval
    
    
    B_GCI_Re_705 <- ((plot[[10]])/(plot[[7]]))-1 # Green Chlorophyll Index with Rededge705 // Improve LAI prediction; The reﬂectance in the red-edge spectral region is comparatively sensitive to chlorophyll content which is highly variable between different crops and different phenological states // https://www.researchgate.net/publication/323723081_Vegetation_Indices_Combining_the_Red_and_Red-Edge_Spectral_Information_for_Leaf_Area_Index_Retrieval // Cholorophyll index-red edge705 (chlorophyll;Gitelson et al. 2003)
    B_GCI_Re_740 <- ((plot[[10]])/(plot[[9]]))-1 # Green Chlorophyll Index with Rededge740 // Improve LAI prediction; The reﬂectance in the red-edge spectral region is comparatively sensitive to chlorophyll content which is highly variable between different crops and different phenological states // https://www.researchgate.net/publication/323723081_Vegetation_Indices_Combining_the_Red_and_Red-Edge_Spectral_Information_for_Leaf_Area_Index_Retrieval // Cholorophyll index-red edge705 (chlorophyll;Gitelson et al. 2003)
    
    ##### MxBlue and MxRededge single spectral band ######
    
    Blue_444 <- plot[[1]]
    Blue_475 <- plot[[2]]
    Green_531 <- plot[[3]]
    Green_560 <- plot[[4]]
    Red_650 <- plot[[5]]
    Red_668 <- plot[[6]]
    Red_e_705 <- plot[[7]]
    Red_e_717 <- plot[[8]]
    Red_e_740 <- plot[[9]]
    NIR_842 <- plot[[10]]
    
    
    
    ###### New indices from FieldImageR
    
    B_BI <- sqrt((plot[[5]]^2+plot[[3]]^2+plot[[1]]^2)/3) # Brightness index (Vegetation coverage,water content;Richardson and Wiegand 1977)
    B_SCI <- (plot[[5]]-plot[[3]])/(plot[[5]]+plot[[3]]) # Soil color index (soil color;Mathieu et al., 1998)
    B_GLI_FM <- (2*plot[[3]]-plot[[5]]-plot[[1]])/(2*plot[[3]]+plot[[5]]+plot[[1]]) # Green leaf index (Chlorophyll;Louhaichi et al 2001)
    B_HI <- (2*plot[[5]]-plot[[3]]-plot[[1]])/(plot[[3]]-plot[[1]]) # Primary color HUE index (soil color; Escadafal et al. 1994)
    B_SI <- (plot[[5]]-plot[[1]])/(plot[[5]]+plot[[1]]) # Spectral slope saturation index (Soil color; Escadafal et al. 1994)
    B_HUE <- atan(2*(plot[[1]]-plot[[3]]-plot[[5]])/30.5*(plot[[3]]-plot[[5]])) # Overall HUE index (Soil color; Escadafal et al. 1994); old equation:HUE <- atan((2*(plot[[3]]-plot[[2]]-plot[[1]]))/(30.5*(plot[[2]]-plot[[1]]))) 
    B_BGI <- plot[[1]]/plot[[3]] # Blue green pigment index (chlorophyll, LAI; Zarco-Tejada et al. 2005)
    B_PSRI705 <-  (plot[[5]]-plot[[3]])/(plot[[7]]) # Plant senescence reflectance index (chlorphyll, nitrogen, maturity; Merzlyak et al. 1999)
    B_PSRI740 <-  (plot[[5]]-plot[[3]])/(plot[[9]]) # Plant senescence reflectance index (chlorphyll, nitrogen, maturity; Merzlyak et al. 1999)
    
    B_NDRE705 <- (plot[[10]]-plot[[7]])/(plot[[10]]+plot[[7]]) # Normalize difference red-edge index (Chlorophll; Gitelson and Merzlyak 1994)
    B_NDRE705_740 <- (plot[[10]]-plot[[7]])/(plot[[10]]+plot[[9]]) # Normalize difference red-edge index (Chlorophll; Gitelson and Merzlyak 1994)
    B_NDRE740 <- (plot[[10]]-plot[[9]])/(plot[[10]]+plot[[9]]) # Normalize difference red-edge index (Chlorophll; Gitelson and Merzlyak 1994)
    B_TVI_B <- 0.5*(120*(plot[[10]]-plot[[3]])-200*(plot[[5]]-plot[[3]])) # Triangular vegetation index (Green LAI, chlorophyll, canopy; Broge and Leblanc 2000)
  
    B_DVI_New705 <- plot[[10]]-plot[[7]] # Difference vegetation index with Re705 (Nitrogen, Chlorophyll; Jordan 1969)
    B_DVI_New740 <- plot[[10]]-plot[[9]] # Difference vegetation index with Re740 (Nitrogen, Chlorophyll; Jordan 1969)

    
    ########## MXRedEdge BANDS #####################################
    
    #Multispectral indices
    R_MCARI717_MTVI2_Arg <- (((plot[[8]]-plot[[6]])-0.2*(plot[[8]]-plot[[4]]))*(plot[[8]]/plot[[6]]))/ (1.5*(2.5*(plot[[10]]-plot[[6]])-1.3*(plot[[10]]-plot[[4]]))/((2*plot[[10]]+1)^2-(6*plot[[10]]-5*plot[[6]]^0.5))^0.5) #Ratio of Modified chlorophyll absorption in reflectance index with Rede717 with MTVI2_Arg // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.// (Basso et al. 2016)
    
    
    R_MCARI717_MTVI <- (((plot[[8]]-plot[[6]])-0.2*(plot[[8]]-plot[[4]]))*(plot[[8]]/plot[[6]]))/(1.2*(1.2 * (plot[[10]] - plot[[4]])-2.5*(plot[[6]]-plot[[4]]))) # Ratio of Modified chlorophyll absorption in reflectance index with Rede717 with MTVI // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.// (Basso et al. 2016)
    
    
    R_MCARI717_OSAVI_B<- (((plot[[8]]-plot[[6]])-0.2*(plot[[8]]-plot[[4]]))*(plot[[8]]/plot[[6]]))/ ((1 + 0.16)*(plot[[10]] - plot[[6]])/(plot[[10]] + plot[[6]] + 0.16)) # Ratio of Modified chlorophyll absorption in reflectance index with Rede717 with OSAVI_B // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.// (Basso et al. 2016)
    
    
    R_TCARI717_OSAVI_B <- (3*((plot[[8]]-plot[[6]])-0.2*(plot[[8]]-plot[[3]])*(plot[[8]]/plot[[6]])))/((1 + 0.16)*(plot[[10]] - plot[[6]])/(plot[[10]] + plot[[6]] + 0.16)) # Ratio of TCARI with Re705 with OSAVI // Nitrogen// (Basso et al. 2016)
    
    R_NDRE717_NDVI <- ((plot[[10]]-plot[[8]])/(plot[[10]]+plot[[9]]))/((plot[[10]]-plot[[6]])/(plot[[10]]+plot[[6]])) # Ratio of Normalize difference red-edge index with NDVI (Chlorophll; Gitelson and Merzlyak 1994)//  (Basso et al. 2016)
    
    R_NDVI_Re_717_NDVI <- ((plot[[8]]-plot[[6]])/(plot[[8]]+plot[[6]]))/((plot[[10]]-plot[[6]])/(plot[[10]]+plot[[6]])) # Ratio of Normalized difference vegetation index with rededge717 instaed of NIR and NDVI
    
    R_TCARI717 <- 3 * ((plot[[8]] - plot[[6]]) - 0.2 * (plot[[8]] - plot[[4]]) * (plot[[8]]/plot[[6]])) # TCARI with Re705 // Nitrogen// (Basso et al. 2016)
    R_CARI717 <- (plot[[8]] - plot[[6]]) - 0.2 * (plot[[8]] - plot[[4]]) # CARI with Re717 // Nitrogen// (Basso et al. 2016)
    R_MTCI717 <- (plot[[10]] - plot[[8]])/(plot[[8]] - plot[[6]]) # MTCI with Re717// Nitrogen // (Basso et al. 2016)
    R_SR <- plot[[10]]/plot[[6]] # simple ratio index // Easy to understand and is effective over a wide range of conditions //Can saturate in dense vegetation when LAI becomes very high.//  (Birth, G., and G. McVey. "Measuring the Color of Growing Turf with a Reflectance Spectrophotometer." Agronomy Journal 60 (1968): 640-643.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html # Also called RVI //Ratio vegetation index // Biomass, water content,nitrogen // Pearson and Miller (1972)//https://raw.githubusercontent.com/filipematias23/images/master/readme/F6ind3.jpeg 
    R_CRE717 <- plot[[10]]/plot[[8]] - 1
    
    R_NDVI <- (plot[[10]]-plot[[6]])/(plot[[10]]+plot[[6]]) # Normalized difference vegetation index // measure of healthy, green vegetation // saturate in dense vegetation conditions when LAI becomes high.// Rouse, J., R. Haas, J. Schell, and D. Deering. Monitoring Vegetation Systems in the Great Plains with ERTS. Third ERTS Symposium, NASA (1973): 309-317. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    R_NDVI_Re_717 <- (plot[[8]]-plot[[6]])/(plot[[8]]+plot[[6]]) # Normalized difference vegetation index with rededge717 instaed of NIR
    
    R_SAVI <- (1.5*(plot[[10]]-plot[[6]]))/(plot[[10]]+plot[[6]]+0.5) # Soil adjusted vegetation index // Best used in areas with relatively sparse vegetation where soil is visible through the canopy // similar to NDVI, but it suppresses the effects of soil pixels// Huete, A. "A Soil-Adjusted Vegetation Index (SAVI)." Remote Sensing of Environment 25 (1988): 295-309.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    R_MSAVI2 <-(2*plot[[10]]+1-sqrt((2*plot[[10]]+1)^2-8*(plot[[10]]-plot[[6]])))/2 # Modified soil adjusted vegetation index 2//  Reduces soil noise and increases the dynamic range of the vegetation signal //  Qi, J., A. Chehbouni, A. Huete, Y. Kerr, and S. Sorooshian. "A Modified Soil Adjusted Vegetation Index." Remote Sensing of Environment 48 (1994): 119-126. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    R_OSAVI <- (plot[[10]]-plot[[6]])/(plot[[10]]+plot[[6]]+0.16) # Optimized soil adjusted vegetation index // This index is best used in areas with relatively sparse vegetation where soil is visible through the canopy // Rondeaux, G., M. Steven, and F. Baret. "Optimization of Soil-Adjusted Vegetation Indices." Remote Sensing of Environment 55 (1996): 95-107. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    R_OSAVI_B <- (1 + 0.16)*(plot[[10]] - plot[[6]])/(plot[[10]] + plot[[6]] + 0.16) # Optimized soil adjusted vegetation index based on Basso publication // (Basso et al. 2016)
    
    
    R_EVI <- 2.5*(plot[[10]]-plot[[6]])/(plot[[10]]+6*plot[[6]]-7.5*plot[[2]]+1) # Enhanced vegetation index //Improvement over NDVI by optimizing the vegetation signal in areas of high leaf area index (LAI)//Huete, A., et al. "Overview of the Radiometric and Biophysical Performance of the MODIS Vegetation Indices."Remote Sensing of Environment 83 (2002):195-213. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html
    R_TVI_R <- sqrt((plot[[10]]-plot[[6]])/(plot[[10]]+plot[[6]])+0.05) # Triangular vegetation index // can be utilized to follow grain crop development from seed bed preparation to harvest// Rouse Jr, J. W., Haas, R. H., Deering, D. W., Schell, J. A., & Harlan, J. C. (1974). Monitoring the vernal advancement and retrogradation (green wave effect) of natural vegetation (No. E75-10354).
    
    # N content in canopy indices
    R_MTVI <- 1.2*(1.2 * (plot[[10]] - plot[[4]])-2.5*(plot[[6]]-plot[[4]]))
    R_MTVI2_Arg <- 1.5*(2.5*(plot[[10]]-plot[[6]])-1.3*(plot[[10]]-plot[[4]]))/((2*plot[[10]]+1)^2-(6*plot[[10]]-5*plot[[6]]^0.5))^0.5 # modified triangular vegetation index 2 // Canopy N content prediction //  Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.
    R_MTVI2_Hab <- (1.5*(1.2*(plot[[10]]-plot[[4]])-2.5*(plot[[6]]-plot[[4]])))/(sqrt((2*plot[[10]]+1)^2-(6*plot[[10]]-5*sqrt(plot[[6]]))-0.5)) # (Haboudane et al., 2004.) (Bagheri et al. 2013)
    R_MCARI_Arg717 <- ((plot[[8]]-plot[[6]])-0.2*(plot[[8]]-plot[[4]]))*(plot[[8]]/plot[[6]]) # Modified chlorophyll absorption in reflectance index with Rede717 // N canopy content prediction// Argento, F., Anken, T., Abt, F., Vogelsanger, E., Walter, A., & Liebisch, F. (2021). Site-specific nitrogen management in winter wheat supported by low-altitude remote sensing and soil data. Precision Agriculture, 22(2), 364-386.
    R_MCARI2_Hab <- (1.5*(2.5*(plot[[10]]-plot[[6]])-1.3*(plot[[10]]-plot[[4]])))/(sqrt((2*plot[[10]]+1)^2-(6*plot[[10]]-5*sqrt(plot[[6]]))-0.5)) # Modified Chlorophyll Absorption Ratio Index Improved // similar to MCARI but is considered a better predictor of green leaf area index (LAI). It incorporates a soil adjustment factor while preserving sensitivity to LAI and resistance to chlorophyll influence.// Haboudane, D., et al. "Hyperspectral Vegetation Indices and Novel Algorithms for Predicting Green LAI of Crop Canopies: Modeling and Validation in the Context of Precision Agriculture." Remote Sensing of Environment 90 (2004): 337-352. // https://www.l3harrisgeospatial.com/docs/narrowbandgreenness.html 
    
    # Chlorophyll index
    
    R_CVI <- (plot[[10]]*plot[[6]])/(plot[[4]]^2) # Chlorophyll vegetation index // Vincini, M., Frazzi, E. R. M. E. S., & D'Alessio, P. A. O. L. O. (2008). A broad-band leaf chlorophyll vegetation index at the canopy scale. Precision Agriculture, 9(5), 303-319. // https://raw.githubusercontent.com/filipematias23/images/master/readme/F6ind3.jpeg
    R_CVI_B <- (plot[[10]]/plot[[4]]) * (plot[[6]]/plot[[4]]) # Chlorophyll vegetation index //(Basso et al. 2016)
    R_gNDVI <- (plot[[10]]-plot[[4]])/(plot[[10]]+plot[[4]]) # Green normalized difference vegetation index // similar to NDVI except that it measures the green spectrum from 540 to 570 nm instead of the red spectrum. This index is more sensitive to chlorophyll concentration than NDVI //Gitelson, A., and M. Merzlyak. "Remote Sensing of Chlorophyll Concentration in Higher Plant Leaves." Advances in Space Research 22 (1998): 689-692.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green
    R_GCI <- (plot[[10]]/plot[[4]])-1 # Green Chlorophyll Index also called CGM (Basso et al. 2016)// This index is used to estimate leaf chlorophyll content across a wide range of plant species. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green // Gitelson, A., Y. Gritz, and M. Merzlyak. "Relationships Between Leaf Chlorophyll Content and Spectral Reflectance and Algorithms for Non-Destructive Chlorophyll Assessment in Higher Plant Leaves." Journal of Plant Physiology 160 (2003): 271-282.
    
    #RGB indices
    
    R_GLI_Har <- ((plot[[4]]-plot[[6]])+(plot[[4]]-plot[[2]]))/((2*plot[[4]])+plot[[6]]+plot[[2]]) # Green Leaf Index // This index was originally designed for use with a digital RGB camera to measure wheat cover, where the red, green, and blue digital numbers (DNs) range from 0 to 255 // Louhaichi, M., M. Borman, and D. Johnson. "Spatially Located Platform and Aerial Photography for Documentation of Grazing Impacts on Wheat." Geocarto International 16, No. 1 (2001): 65-70. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green
    R_NGRDI <- (plot[[4]]-plot[[6]])/(plot[[4]]+plot[[6]]) # Normalized green red difference index // Chlorophyll, biomass and water content prediction // Tucker, C. J. (1979). Red and photographic infrared linear combinations for monitoring vegetation. Remote sensing of Environment, 8(2), 127-150.// https://raw.githubusercontent.com/filipematias23/images/master/readme/F6ind3.jpeg
    R_VARI <- (plot[[4]]-plot[[6]])/(plot[[4]]+plot[[6]]-plot[[2]]) # Visible atmospherically resistant index // This index is based on the ARVI and is used to estimate the fraction of vegetation in a scene with low sensitivity to atmospheric effects.// Gitelson, A., et al. "Vegetation and Soil Lines in Visible Spectral Space: A Concept and Technique for Remote Estimation of Vegetation Fraction. International Journal of Remote Sensing 23 (2002): 2537???2562.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green
    
    R_TGI <- plot[[4]]-0.39*plot[[6]]-0.61*plot[[2]] # Triangular greenness index surrogate, following https://agribotix.com/blog/2017/04/30/comparing-rgb-based-vegetation-indices-with-ndvi-for-agricultural-drone-imagery// From Simon Treier
    R_TGI_Har <- ((650-444)*(plot[[6]]-plot[[4]])-(650-531)*(plot[[6]]-plot[[2]]))/2 # Triangular Greenness Index // The TGI is highly correlated with leaf chlorophyll content.// Hunt, E., C. Daughtry, J. Eitel, and D. Long. "Remote Sensing Leaf Chlorophyll Content Using a Visible Band Index." Agronomy Journal 103, No. 4 (2011): 1090-1099.//https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Visible
    
    R_MNVI <- 2*(plot[[4]])-2*(plot[[2]])-2.4*(plot[[6]]) # // difference between the excess green (EGVI = 2G-R-B) and excess red (ERVI = 1.4R-B) // plant density prediction // Jin, X., Liu, S., Baret, F., Hemerl?, M., & Comar, A. (2017). Estimates of plant density of wheat crops at emergence from very low altitude UAV imagery. Remote Sensing of Environment, 198, 105-114.
    
    #Other multispectral indices
    
    R_DVI <- plot[[10]]-plot[[6]] # Difference Vegetation Index // distinguishes between soil and vegetation, but it does not account for the difference between reflectance and radiance caused by atmospheric effects or shadows.// Tucker, C. "Red and Photographic Infrared Linear Combinations for Monitoring Vegetation. Remote Sensing of Environment 8 (1979): 127-150. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Differen
    R_GEMI <- ((2*(plot[[10]]^2-plot[[6]]^2)+1.5*plot[[10]]+0.5*plot[[6]])/(plot[[10]]+plot[[6]]+0.5))*(1-0.25*((2*(plot[[10]]^2-plot[[6]]^2)+1.5*plot[[10]]+0.5*plot[[6]])/(plot[[10]]+plot[[6]]+0.5)))-(plot[[6]]-0.125)/(1-plot[[6]]) # Global Environmental Monitoring Index // It is similar to NDVI but is less sensitive to atmospheric effects // It is affected by bare soil; therefore, it is not recommended for use in areas of sparse or moderately dense vegetation. // Pinty, B., and M. Verstraete. GEMI: a Non-Linear Index to Monitor Global Vegetation From Satellites. Vegetation 101 (1992): 15-20. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Global
    R_GARI <- (plot[[10]]-(plot[[4]]-1.7*(plot[[2]]-plot[[6]])))/(plot[[10]]+(plot[[4]]-1.7*(plot[[6]]-plot[[2]]))) # Green Atmospherically Resistant Index // more sensitive to a wide range of chlorophyll concentrations and less sensitive to atmospheric effects than NDVI. // Gitelson, A., Y. Kaufman, and M. Merzylak. "Use of a Green Channel in Remote Sensing of Global Vegetation from EOS-MODIS." Remote Sensing of Environment 58 (1996): 289-298. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green2
    R_GDVI <- plot[[10]]-plot[[4]] # Green Difference Vegetation Index // was originally designed with color-infrared photography to predict nitrogren requirements for corn.// Sripada, R., et al. "Determining In-Season Nitrogen Requirements for Corn Using Aerial Color-Infrared Photography." Ph.D. dissertation, North Carolina State University, 2005. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green2
    R_GOSAVI <- (plot[[10]]-plot[[4]])/(plot[[10]]+plot[[4]]+0.16) # Green Optimized Soil Adjusted Vegetation Index // designed with color-infrared photography to predict nitrogren requirements for corn. It is similar to OSAVI, but it substitutes the green band for red.//Sripada, R., et al. "Determining In-Season Nitrogen Requirements for Corn Using Aerial Color-Infrared Photography." Ph.D. dissertation, North Carolina State University, 2005.//https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green9 
    R_GRVI <- plot[[10]]/plot[[4]] # Green Ratio Vegetation Index //  sensitive to photosynthetic rates in forest canopies, as green and red reflectances are strongly influenced by changes in leaf pigments. // Sripada, R., et al. "Aerial Color Infrared Photography for Determining Early In-season Nitrogen Requirements in Corn." Agronomy Journal 98 (2006): 968-977.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green4
    R_GSAVI <- 1.5*(plot[[10]]-plot[[4]])/(plot[[10]]+plot[[4]]+0.5) # Green Soil Adjusted Vegetation Index // Originally designed with color-infrared photography to predict nitrogren requirements for corn. It is similar to SAVI, but it substitutes the green band for red.//Sripada, R., et al. "Determining In-Season Nitrogen Requirements for Corn Using Aerial Color-Infrared Photography." Ph.D. dissertation, North Carolina State University, 2005.//https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green8
    R_IPVI <- plot[[10]]/(plot[[10]]+plot[[6]]) # Infrared Percentage Vegetation Index//functionally the same as NDVI, but it is computationally faster. Values range from 0 to 1. // Crippen, R. "Calculating the Vegetation Index Faster." Remote Sensing of Environment 34 (1990): 71-73. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green4
    R_LAI <- 3.618*(2.5*(plot[[10]]-plot[[6]])/(plot[[10]]+6*plot[[6]]-7.5*plot[[2]]+1))-0.118 # Leaf Area Index // used to estimate foliage cover and to forecast crop growth and yield.// Boegh, E., H. Soegaard, N. Broge, C. Hasager, N. Jensen, K. Schelde, and A. Thomsen. "Airborne Multi-spectral Data for Quantifying Leaf Area Index, Nitrogen Concentration and Photosynthetic Efficiency in Agriculture." Remote Sensing of Environment 81, no. 2-3 (2002): 179-193. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Leaf
    R_GVI <- (-0.2848*plot[[2]])+(-0.2435*plot[[4]])+(-0.5436*plot[[6]])+(0.7243*plot[[10]]) # Green Vegetation Index // This index minimizes the effects of background soil while emphasizing green vegetation // Kauth, R., and G. Thomas. "The Tasselled Cap-A Graphic Description of the Spectral-Temporal Development of Agricultural Crops as Seen By Landsat" In Proceedings of the LARS 1976 Symposium of Machine Processing of Remotely-Sensed Data, West Lafayette, IN: Purdue University, pp. 4B41-4B51. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Green5
    R_MNLI <- ((plot[[10]]^2-plot[[6]])*(1+0.5))/(plot[[10]]^2+plot[[6]]+0.5) # Modified Non-Linear Index // enhancement to the Non-Linear Index (NLI) that incorporates the Soil Adjusted Vegetation Index (SAVI) to account for the soil background // Yang, Z., P. Willis, and R. Mueller. "Impact of Band-Ratio Enhanced AWIFS Image to Crop Classification Accuracy." Proceedings of the Pecora 17 Remote Sensing Symposium (2008), Denver, CO. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Modified2
    R_MSR <- ((plot[[10]]/plot[[6]])-1)/((sqrt(plot[[10]]/plot[[6]]))+1) # Modified Simple Ratio // improvement over RDVI by combining the Simple Ratio into the formula. The result is increased sensitivity to vegetation biophysical parameters // Chen, J. "Evaluation of Vegetation Indices and Modified Simple Ratio for Boreal Applications." Canadian Journal of Remote Sensing 22 (1996): 229-242. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Modified
    R_NLI <- (plot[[10]]^2-plot[[6]])/(plot[[10]]^2+plot[[6]]) # Non-Linear Index // relationship between many vegetation indices and surface biophysical parameters is non-linear. // Goel, N., and W. Qin. "Influences of Canopy Architecture on Relationships Between Various Vegetation Indices and LAI and Fpar: A Computer Simulation." Remote Sensing Reviews 10 (1994): 309-347. // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Non-Line
    R_RDVI <- (plot[[10]]-plot[[6]])/sqrt(plot[[10]]+plot[[6]]) # Renormalized Difference Vegetation Index // This index uses the difference between near-infrared and red wavelengths, along with the NDVI, to highlight healthy vegetation. It is insensitive to the effects of soil and sun viewing geometry.// Roujean, J., and F. Breon. "Estimating PAR Absorbed by Vegetation from Bidirectional Reflectance Measurements." Remote Sensing of Environment 51 (1995): 375-384.//https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Renormal
    R_TDVI <- 1.5*((plot[[10]]-plot[[6]])/sqrt(plot[[10]]^2+plot[[6]]+0.5)) # Transformed Difference Vegetation Index // Useful for monitoring vegetation cover in urban environments. It does not saturate like NDVI and SAVI.// Bannari, A., H. Asalhi, and P. Teillet. "Transformed Difference Vegetation Index (TDVI) for Vegetation Cover Mapping" In Proceedings of the Geoscience and Remote Sensing Symposium, IGARSS '02, IEEE International, Volume 5 (2002). // https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Transfor2
    R_WDRVI <- (0.2*plot[[10]]-plot[[6]])/(0.2*plot[[10]]+plot[[6]]) # Wide Dynamic Range Vegetation Index // similar to NDVI, but it uses a weighting coefficient (a) to reduce the disparity between the contributions of the near-infrared and red signals to the NDVI. The WDRVI is particularly effective in scenes that have moderate-to-high vegetation density when NDVI exceeds 0.6. // Gitelson, A. "Wide Dynamic Range Vegetation Index for Remote Quantification of Biophysical Characteristics of Vegetation." Journal of Plant Physiology 161, No. 2 (2004): 165-173.// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#Wide
    
    R_WVVI_717 <- (plot[[10]]-plot[[6]])/(plot[[8]]+plot[[6]]) # WorldView Improved Vegetative Index // This index uses WorldView-2 bands (here replaced by red-edge band717) to compute NDVI.// Wolf, A. Using WorldView 2 Vis-NIR MSI Imagery to Support Land Mapping and Feature Extraction Using Normalized Difference Index Ratios. Unpublished report, Longmont, CO: DigitalGlobe (2010).// https://www.l3harrisgeospatial.com/docs/broadbandgreenness.html#WorldVie2
    
    R_MSR_Re_717 <- ((plot[[10]])/(plot[[8]])-1)/(((plot[[10]])/(plot[[8]])+1)^0.5) # Modified Simple Ratio with Rededge717 // Improve LAI prediction; The reﬂectance in the red-edge spectral region is comparatively sensitive to chlorophyll content which is highly variable between different crops and different phenological states // https://www.researchgate.net/publication/323723081_Vegetation_Indices_Combining_the_Red_and_Red-Edge_Spectral_Information_for_Leaf_Area_Index_Retrieval
    
    R_GCI_Re_717 <- ((plot[[10]])/(plot[[8]]))-1 # Green Chlorophyll Index with Rededge717 // Improve LAI prediction; The reﬂectance in the red-edge spectral region is comparatively sensitive to chlorophyll content which is highly variable between different crops and different phenological states // https://www.researchgate.net/publication/323723081_Vegetation_Indices_Combining_the_Red_and_Red-Edge_Spectral_Information_for_Leaf_Area_Index_Retrieval //  Cholorophyll index-red edge705 (chlorophyll;Gitelson et al. 2003)
    
    ###### New indices from FieldImageR
    
    R_BI <- sqrt((plot[[6]]^2+plot[[4]]^2+plot[[2]]^2)/3) # Brightness index (Vegetation coverage,water content;Richardson and Wiegand 1977)
    R_SCI <- (plot[[6]]-plot[[4]])/(plot[[6]]+plot[[4]]) # Soil color index (soil color;Mathieu et al., 1998)
    R_GLI_FM <- (2*plot[[4]]-plot[[6]]-plot[[2]])/(2*plot[[4]]+plot[[6]]+plot[[2]]) # Green leaf index (Chlorophyll;Louhaichi et al 2001)
    R_HI <- (2*plot[[6]]-plot[[4]]-plot[[2]])/(plot[[4]]-plot[[2]]) # Primary color HUE index (soil color; Escadafal et al. 1994)
    R_SI <- (plot[[6]]-plot[[2]])/(plot[[6]]+plot[[2]]) # Spectral slope saturation index (Soil color; Escadafal et al. 1994)
    R_HUE <- atan(2*(plot[[2]]-plot[[4]]-plot[[6]])/30.5*(plot[[4]]-plot[[6]])) # Overall HUE index (Soil color; Escadafal et al. 1994); old equation:HUE <- atan((2*(plot[[4]]-plot[[2]]-plot[[2]]))/(30.5*(plot[[2]]-plot[[2]]))) 
    R_BGI <- plot[[2]]/plot[[4]] # Blue green pigment index (chlorophyll, LAI; Zarco-Tejada et al. 2005)
    R_PSRI717 <-  (plot[[6]]-plot[[4]])/(plot[[8]]) # Plant senescence reflectance index (chlorphyll, nitrogen, maturity; Merzlyak et al. 1999)
    
    R_NDRE717 <- (plot[[10]]-plot[[8]])/(plot[[10]]+plot[[8]]) # Normalize difference red-edge index (Chlorophll; Gitelson and Merzlyak 1994)
    R_NDRE717_740 <- (plot[[10]]-plot[[8]])/(plot[[10]]+plot[[9]]) # Normalize difference red-edge index (Chlorophll; Gitelson and Merzlyak 1994)
    R_NDRE717_705 <- (plot[[10]]-plot[[8]])/(plot[[10]]+plot[[7]]) # Normalize difference red-edge index (Chlorophll; Gitelson and Merzlyak 1994)
    
    
    R_TVI_B <- 0.5*(120*(plot[[10]]-plot[[4]])-200*(plot[[6]]-plot[[4]])) # Triangular vegetation index (Green LAI, chlorophyll, canopy; Broge and Leblanc 2000)

    R_DVI_New717 <- plot[[10]]-plot[[8]] # Difference vegetation index with Re717 (Nitrogen, Chlorophyll; Jordan 1969)
    
    
    RGB_Indices <- stack(R_MCARI717_MTVI2_Arg,B_MCARI705_MTVI2_Arg,B_MCARI740_MTVI2_Arg,R_MCARI717_MTVI,B_MCARI705_MTVI,B_MCARI740_MTVI,R_MCARI717_OSAVI_B,B_MCARI705_OSAVI_B,B_MCARI740_OSAVI_B,R_TCARI717_OSAVI_B,B_TCARI705_OSAVI_B,B_TCARI740_OSAVI_B,R_NDRE717_NDVI,B_NDRE705_NDVI,B_NDRE740_NDVI,R_NDVI_Re_717_NDVI,B_NDVI_Re_705_NDVI,B_NDVI_Re_740_NDVI,B_TCARI705,B_TCARI740,R_TCARI717, B_CARI705,B_CARI740,R_CARI717,B_MTCI705,B_MTCI740,R_MTCI717,B_SR,B_CRE705,B_CRE740,B_NDVI,B_NDVI_Re_705,B_NDVI_Re_740,B_SAVI,B_MSAVI2,B_OSAVI_B,B_OSAVI,B_EVI,B_TVI_R,B_MTVI,B_MTVI2_Arg,B_MTVI2_Hab,B_MCARI_Arg705,B_MCARI_Arg740,B_MCARI2_Hab,B_CVI_B,B_CVI,B_gNDVI,B_GCI,B_GLI_Har,B_NGRDI,B_VARI,B_TGI,B_TGI_Har,B_MNVI,B_DVI,B_GEMI,B_GARI,B_GDVI,B_GOSAVI,B_GRVI,B_GSAVI,B_IPVI,B_LAI,B_GVI,B_MNLI,B_MSR,B_NLI,B_RDVI,B_TDVI,B_WDRVI,B_WVVI_705,B_WVVI_740,B_MSR_Re_705,B_MSR_Re_740,B_GCI_Re_705,B_GCI_Re_740,Blue_444,Blue_475,Green_531,Green_560,Red_650,Red_668,Red_e_705,Red_e_717,Red_e_740,NIR_842,B_BI,B_SCI,B_GLI_FM,B_HI,B_SI,B_HUE,B_BGI,B_PSRI705,B_PSRI740,B_NDRE705,B_NDRE705_740,B_NDRE740,B_TVI_B,B_DVI_New705,B_DVI_New740,R_SR,R_CRE717,R_NDVI,R_NDVI_Re_717,R_SAVI,R_MSAVI2,R_OSAVI_B,R_OSAVI,R_EVI,R_TVI_R,R_MTVI,R_MTVI2_Arg,R_MTVI2_Hab,R_MCARI_Arg717,R_MCARI2_Hab,R_CVI_B,R_CVI,R_gNDVI,R_GCI,R_GLI_Har,R_NGRDI,R_VARI,R_TGI,R_TGI_Har,R_MNVI,R_DVI,R_GEMI,R_GARI,R_GDVI,R_GOSAVI,R_GRVI,R_GSAVI,R_IPVI,R_LAI,R_GVI,R_MNLI,R_MSR,R_NLI,R_RDVI,R_TDVI,R_WDRVI,R_WVVI_717,R_MSR_Re_717,R_GCI_Re_717,R_BI,R_SCI,R_GLI_FM,R_HI,R_SI,R_HUE,R_BGI,R_PSRI717,R_NDRE717,R_NDRE717_740,R_NDRE717_705,R_TVI_B,R_DVI_New717) # Stack all indixes of a subplot into one raster
    names(RGB_Indices) <- c("R_MCARI717_MTVI2_Arg","B_MCARI705_MTVI2_Arg","B_MCARI740_MTVI2_Arg","R_MCARI717_MTVI","B_MCARI705_MTVI","B_MCARI740_MTVI","R_MCARI717_OSAVI_B","B_MCARI705_OSAVI_B","B_MCARI740_OSAVI_B","R_TCARI717_OSAVI_B","B_TCARI705_OSAVI_B","B_TCARI740_OSAVI_B","R_NDRE717_NDVI","B_NDRE705_NDVI","B_NDRE740_NDVI","R_NDVI_Re_717_NDVI","B_NDVI_Re_705_NDVI","B_NDVI_Re_740_NDVI","B_TCARI705","B_TCARI740","R_TCARI717","B_CARI705","B_CARI740","R_CARI717","B_MTCI705","B_MTCI740","R_MTCI717","B_SR","B_CRE705","B_CRE740","B_NDVI","B_NDVI_Re_705","B_NDVI_Re_740","B_SAVI","B_MSAVI2","B_OSAVI_B","B_OSAVI","B_EVI","B_TVI_R","B_MTVI","B_MTVI2_Arg","B_MTVI2_Hab","B_MCARI_Arg705","B_MCARI_Arg740","B_MCARI2_Hab","B_CVI","B_CVI_B","B_gNDVI","B_GCI","B_GLI_Har","B_NGRDI","B_VARI","B_TGI","B_TGI_Har","B_MNVI","B_DVI","B_GEMI","B_GARI","B_GDVI","B_GOSAVI","B_GRVI","B_GSAVI","B_IPVI","B_LAI","B_GVI","B_MNLI","B_MSR","B_NLI","B_RDVI","B_TDVI","B_WDRVI","B_WVVI_705","B_WVVI_740","B_MSR_Re_705","B_MSR_Re_740","B_GCI_Re_705","B_GCI_Re_740","Blue_444","Blue_475","Green_531","Green_560","Red_650","Red_668","Red_e_705","Red_e_717","Red_e_740","NIR_842","B_BI","B_SCI","B_GLI_FM","B_HI","B_SI","B_HUE","B_BGI","B_PSRI705","B_PSRI740","B_NDRE705","B_NDRE705_740","B_NDRE740","B_TVI_B","B_DVI_New705","B_DVI_New740","R_SR","R_CRE717","R_NDVI","R_NDVI_Re_717","R_SAVI","R_MSAVI2","R_OSAVI_B","R_OSAVI","R_EVI","R_TVI_R","R_MTVI","R_MTVI2_Arg","R_MTVI2_Hab","R_MCARI_Arg717","R_MCARI2_Hab","R_CVI_B","R_CVI","R_gNDVI","R_GCI","R_GLI_Har","R_NGRDI","R_VARI","R_TGI","R_TGI_Har","R_MNVI","R_DVI","R_GEMI","R_GARI","R_GDVI","R_GOSAVI","R_GRVI","R_GSAVI","R_IPVI","R_LAI","R_GVI","R_MNLI","R_MSR","R_NLI","R_RDVI","R_TDVI","R_WDRVI","R_WVVI_717","R_MSR_Re_717","R_GCI_Re_717","R_BI","R_SCI","R_GLI_FM","R_HI","R_SI","R_HUE","R_BGI","R_PSRI717","R_NDRE717","R_NDRE717_740","R_NDRE717_705","R_TVI_B","R_DVI_New717") # Name the layers in the raster
    
    #plot(RGB_Indices[[1]])
    #outpath <- gsub(".shp",".tif",outpath)
    #png(file = outpath, bg = "transparent")
    #plotRGB(plot)
    #dev.off()
    #outpath <- gsub(".tif","NDVI.tif",outpath)
    #png(file = outpath, bg = "transparent")
    #plot(NDVI)
    #dev.off() 
    #outpath <- gsub("NDVI.tif","HIST.tif",outpath)
    #png(file = outpath)
    #hist(NDVI,breaks=seq(-0.5,1,0.025),xlim=c(-0.5,1), main=paste("Histogram", outfile))
    #dev.off()
    Name <- gsub(".shp","",outfile) # Defining a name for the data frame entry
    ID <- sub(".*\\_id_","",Name) # Extract the ID from the name
    
    Stat_data_Line <- data.frame(matrix(NA, nrow = 1, ncol = length(Tablenames))) # Create an empty data frame to be filled with data later on
    names(Stat_data_Line) <- Tablenames # Add the names to the stat_data_Line
    
    for(k in 1:length(names(RGB_Indices))){ # According to the names in "Tablenames", data is genereated her, one line for each indices per subplot and date.hight
      StatNewRow <- c(names(RGB_Indices[[k]]),ID,Name,cellStats(RGB_Indices[[k]], "mean"),cellStats(RGB_Indices[[k]], "sd"),quantile(RGB_Indices[[k]],
                                                                                                                                     probs = Quantiles, type=7,names = FALSE),DateHight[j],Orthofilenames[j])
      Stat_data_Line <- rbind(Stat_data_Line,StatNewRow) # Bind the tables Stat_data_Line and StatNewRow
    }
    Stat_data_Line <- Stat_data_Line[!is.na(Stat_data_Line$Name),] # Clear empty entries from Stat_Data_Line
    Stat_data <- rbind(Stat_data_Line,Stat_data) # Bind the tables Stat_data_Line and StatData
    Stat_data <- Stat_data[!is.na(Stat_data$Name),] # Clear empty entries from Stat_data
  }
  
  # Combining and writing tables ----
  
  write.table(Stat_data, file = paste0(Orthofilenames[j], ColorSpace,"table.txt"), sep = ",", # Write a .txt file for each date in the respective folder
              row.names = FALSE,col.names = TRUE)
  
}

warnings()

